# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-20 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfoForStatistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_id', models.IntegerField(db_index=True)),
                ('name', models.CharField(max_length=64, verbose_name='\u59d3\u540d')),
                ('id_card', models.CharField(max_length=64, verbose_name='\u8eab\u4efd\u8bc1\u53f7')),
                ('phone', models.CharField(max_length=64, verbose_name='\u624b\u673a\u53f7')),
                ('sex', models.CharField(max_length=8, verbose_name='\u6027\u522b')),
                ('source', models.CharField(default='', max_length=64, validators='\u8d44\u4ea7\u5305\u6807\u7b7e')),
                ('native_province', models.CharField(default='', max_length=128, validators='\u7c4d\u8d2f\u7701')),
                ('native_city', models.CharField(default='', max_length=128, validators='\u7c4d\u8d2f\u5e02')),
                ('native_district', models.CharField(default='', max_length=128, validators='\u7c4d\u8d2f\u533a')),
                ('native_address', models.CharField(default='', max_length=256, verbose_name='\u7c4d\u8d2f\u8be6\u7ec6\u5730\u5740')),
                ('education', models.CharField(max_length=256, verbose_name='\u6559\u80b2\u7a0b\u5ea6')),
                ('jobs', models.CharField(max_length=256, verbose_name='\u804c\u4e1a')),
                ('live_province', models.CharField(default='', max_length=128, validators='\u5c45\u4f4f\u5730\u7701')),
                ('live_city', models.CharField(default='', max_length=128, validators='\u5c45\u4f4f\u5730\u5e02')),
                ('live_district', models.CharField(default='', max_length=128, validators='\u5c45\u4f4f\u5730\u533a')),
                ('live_address', models.CharField(default='', max_length=256, verbose_name='\u5c45\u4f4f\u5730\u8be6\u7ec6\u5730\u5740')),
                ('application_province', models.CharField(default='', max_length=128, validators='\u7533\u8bf7\u5730\u7701')),
                ('application_city', models.CharField(default='', max_length=128, validators='\u7533\u8bf7\u5730\u5e02')),
                ('application_district', models.CharField(default='', max_length=128, validators='\u7533\u8bf7\u5730\u533a')),
                ('application_address', models.CharField(default='', max_length=256, verbose_name='\u7533\u8bf7\u5730\u8be6\u7ec6\u5730\u5740')),
                ('application_time', models.IntegerField()),
                ('create_time', models.IntegerField()),
            ],
        ),
    ]
