# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-20 20:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfoforstatistics',
            name='application_address',
            field=models.CharField(max_length=256, null=True, verbose_name='\u7533\u8bf7\u5730\u8be6\u7ec6\u5730\u5740'),
        ),
        migrations.AlterField(
            model_name='userinfoforstatistics',
            name='application_city',
            field=models.CharField(max_length=128, null=True, validators='\u7533\u8bf7\u5730\u5e02'),
        ),
        migrations.AlterField(
            model_name='userinfoforstatistics',
            name='application_district',
            field=models.CharField(max_length=128, null=True, validators='\u7533\u8bf7\u5730\u533a'),
        ),
        migrations.AlterField(
            model_name='userinfoforstatistics',
            name='application_province',
            field=models.CharField(max_length=128, null=True, validators='\u7533\u8bf7\u5730\u7701'),
        ),
        migrations.AlterField(
            model_name='userinfoforstatistics',
            name='education',
            field=models.CharField(max_length=256, null=True, verbose_name='\u6559\u80b2\u7a0b\u5ea6'),
        ),
        migrations.AlterField(
            model_name='userinfoforstatistics',
            name='jobs',
            field=models.CharField(max_length=256, null=True, verbose_name='\u804c\u4e1a'),
        ),
        migrations.AlterField(
            model_name='userinfoforstatistics',
            name='live_address',
            field=models.CharField(max_length=256, null=True, verbose_name='\u5c45\u4f4f\u5730\u8be6\u7ec6\u5730\u5740'),
        ),
        migrations.AlterField(
            model_name='userinfoforstatistics',
            name='live_city',
            field=models.CharField(max_length=128, null=True, validators='\u5c45\u4f4f\u5730\u5e02'),
        ),
        migrations.AlterField(
            model_name='userinfoforstatistics',
            name='live_district',
            field=models.CharField(max_length=128, null=True, validators='\u5c45\u4f4f\u5730\u533a'),
        ),
        migrations.AlterField(
            model_name='userinfoforstatistics',
            name='live_province',
            field=models.CharField(max_length=128, null=True, validators='\u5c45\u4f4f\u5730\u7701'),
        ),
        migrations.AlterField(
            model_name='userinfoforstatistics',
            name='native_address',
            field=models.CharField(max_length=256, null=True, verbose_name='\u7c4d\u8d2f\u8be6\u7ec6\u5730\u5740'),
        ),
        migrations.AlterField(
            model_name='userinfoforstatistics',
            name='native_city',
            field=models.CharField(max_length=128, null=True, validators='\u7c4d\u8d2f\u5e02'),
        ),
        migrations.AlterField(
            model_name='userinfoforstatistics',
            name='native_district',
            field=models.CharField(max_length=128, null=True, validators='\u7c4d\u8d2f\u533a'),
        ),
        migrations.AlterField(
            model_name='userinfoforstatistics',
            name='native_province',
            field=models.CharField(max_length=128, null=True, validators='\u7c4d\u8d2f\u7701'),
        ),
    ]
