# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-26 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0003_modelfeature_modelfeaturerecord_modelfeaturevectorrecord_modelrunningrecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfoforstatistics',
            name='application_address',
        ),
        migrations.RemoveField(
            model_name='userinfoforstatistics',
            name='application_city',
        ),
        migrations.RemoveField(
            model_name='userinfoforstatistics',
            name='application_district',
        ),
        migrations.RemoveField(
            model_name='userinfoforstatistics',
            name='application_province',
        ),
        migrations.RemoveField(
            model_name='userinfoforstatistics',
            name='live_address',
        ),
        migrations.RemoveField(
            model_name='userinfoforstatistics',
            name='live_city',
        ),
        migrations.RemoveField(
            model_name='userinfoforstatistics',
            name='live_district',
        ),
        migrations.RemoveField(
            model_name='userinfoforstatistics',
            name='live_province',
        ),
        migrations.RemoveField(
            model_name='userinfoforstatistics',
            name='native_address',
        ),
        migrations.RemoveField(
            model_name='userinfoforstatistics',
            name='native_city',
        ),
        migrations.RemoveField(
            model_name='userinfoforstatistics',
            name='native_district',
        ),
        migrations.RemoveField(
            model_name='userinfoforstatistics',
            name='native_province',
        ),
        migrations.AddField(
            model_name='userinfoforstatistics',
            name='application_lat',
            field=models.CharField(max_length=128, null=True, validators='\u7533\u8bf7\u5730\u7ef4\u5ea6'),
        ),
        migrations.AddField(
            model_name='userinfoforstatistics',
            name='application_long',
            field=models.CharField(max_length=128, null=True, validators='\u7533\u8bf7\u5730\u7ecf\u5ea6'),
        ),
        migrations.AddField(
            model_name='userinfoforstatistics',
            name='live_lat',
            field=models.CharField(max_length=128, null=True, validators='\u5c45\u4f4f\u5730\u7ef4\u5ea6'),
        ),
        migrations.AddField(
            model_name='userinfoforstatistics',
            name='live_long',
            field=models.CharField(max_length=128, null=True, validators='\u5c45\u4f4f\u5730\u7ecf\u5ea6'),
        ),
        migrations.AlterModelTable(
            name='userinfoforstatistics',
            table='user_info',
        ),
    ]
